CREATE TABLE breakdown(
  spn_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  spn VARCHAR(255) NOT NULL ,
  fmi VARCHAR(255) NOT NULL ,
  faultMesg VARCHAR(255) NOT NULL,
  faultTime VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;