CREATE DATABASE data_item;

CREATE TABLE t_user(
  item_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  repairItemName VARCHAR(255) NOT NULL ,
  opId VARCHAR(255) NOT NULL ,
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;