
CREATE TABLE item_detail (
  item_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  beforePicUrl VARCHAR(255) ,
  afterPicUrl VARCHAR(255)  ,
  otherPicUrl VARCHAR(255) ,
  repairItemName VARCHAR(255) ,
  userFeedBack VARCHAR(255)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE item_detail(
item_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  beforePicUrl VARCHAR(255) ,
  afterPicUrl VARCHAR(255)  ,
    otherPicUrl VARCHAR(255) ,
  repairItemName VARCHAR(255)  ,
    userFeedBack VARCHAR(255)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

CREATE TABLE service_active_item(
  item_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  activeId VARCHAR(255),
  activeCode VARCHAR(255),
  activeName VARCHAR(255),
  activeComment VARCHAR(255),
  woCode VARCHAR(255),
  status VARCHAR(255),
  opId VARCHAR(255)
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;